#!/usr/bin/env node

/**
 * Performance budget checker.
 *
 * Reads the Next.js bundle analysis output (generated by `ANALYZE=true next build`)
 * and enforces size budgets.  Designed to run in CI after every build.
 *
 * Usage:
 *   node scripts/performance-budget.mjs
 *
 * Exit codes:
 *   0 — all budgets met
 *   1 — one or more budgets exceeded
 *
 * Budgets (per-route first-load JS, gzipped approximations):
 *   - Shared (framework + common chunks): 110 kB
 *   - Dashboard: 200 kB
 *   - Auth pages (login/register): 200 kB
 *   - Any other page: 300 kB
 */

import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// ── Budgets (first-load JS in bytes) ────────────────────────────────────

const BUDGETS = {
  shared: 110_000,
  dashboard: 200_000,
  auth: 200_000,
  default: 300_000,
};

// ── Helpers ─────────────────────────────────────────────────────────────

function loadTrace() {
  // Next.js generates `.next/analyze/` or `.next/build-manifest.json`
  const manifestPath = resolve(ROOT, ".next/build-manifest.json");
  if (!existsSync(manifestPath)) {
    console.warn("⚠  build-manifest.json not found. Run `ANALYZE=true next build` first.");
    return null;
  }
  return JSON.parse(readFileSync(manifestPath, "utf-8"));
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} kB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function routeBudget(route) {
  if (route.startsWith("/dashboard")) return BUDGETS.dashboard;
  if (route.startsWith("/auth")) return BUDGETS.auth;
  return BUDGETS.default;
}

// ── Main ────────────────────────────────────────────────────────────────

let exitCode = 0;

const manifest = loadTrace();
if (manifest) {
  // build-manifest.json contains a `pages` object mapping routes to their JS chunks
  const pages = manifest.pages || {};

  // Compute approximate first-load JS per page
  for (const [route, chunks] of Object.entries(pages)) {
    if (route === "/_app" || route === "/_error") continue;

    let totalSize = 0;
    for (const chunk of chunks) {
      const chunkPath = resolve(ROOT, ".next", chunk);
      if (existsSync(chunkPath)) {
        totalSize += readFileSync(chunkPath).length;
      }
    }

    const budget = routeBudget(route);
    if (totalSize > budget) {
      console.error(
        `❌  ${route.padEnd(30)} ${formatBytes(totalSize).padStart(10)}  exceeds budget ${formatBytes(budget)}`,
      );
      exitCode = 1;
    } else {
      console.log(
        `✅  ${route.padEnd(30)} ${formatBytes(totalSize).padStart(10)}  (budget ${formatBytes(budget)})`,
      );
    }
  }
}

// Check shared chunks
const sharedPath = resolve(ROOT, ".next/static/chunks");
if (existsSync(sharedPath)) {
  const { readdirSync } = await import("fs");
  let sharedSize = 0;
  for (const file of readdirSync(sharedPath)) {
    const stat = readFileSync(resolve(sharedPath, file)).length;
    sharedSize += stat;
  }
  // Shared chunks are aggregated — approximate
  if (sharedSize > BUDGETS.shared * 2) {
    // heuristic: shared is split across framework, vendor, commons
    console.warn(`⚠  Shared chunks total: ${formatBytes(sharedSize)}`);
  }
}

process.exit(exitCode);
