import type { Metadata } from "next";

import { LegalLayout, LegalSection } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy — Tayari AI",
  description: "How Tayari AI collects, uses, and protects your personal information.",
  robots: { index: true, follow: true },
};

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="August 14, 2026">
      <LegalSection heading="1. Overview">
        <p>
          This Privacy Policy explains how Tayari AI ("we", "us", or "our") collects, uses, shares,
          and protects personal information when you use our interview preparation platform,
          website, and related services (collectively, the "Service").
        </p>
        <p>
          By creating an account or using the Service, you agree to the practices described in this
          policy. If you do not agree, please do not use the Service.
        </p>
      </LegalSection>

      <LegalSection heading="2. Information We Collect">
        <p>We collect the following categories of information:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong className="text-foreground">Account information.</strong> Your email address,
            username, display name, and password (stored as a one-way hash).
          </li>
          <li>
            <strong className="text-foreground">Interview data.</strong> Recorded audio,
            transcripts, code submissions, answers, and AI-generated evaluations produced while you
            practice on the Service.
          </li>
          <li>
            <strong className="text-foreground">Usage information.</strong> Pages visited, features
            used, timestamps, and performance metrics that support analytics and progress tracking.
          </li>
          <li>
            <strong className="text-foreground">Device and technical data.</strong> IP address,
            browser type, device identifiers, and logs generated by our infrastructure.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. How We Use Your Information">
        <p>We use collected information to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Provide, operate, and improve the Service, including generating interview questions and
            evaluations.
          </li>
          <li>Authenticate your account and keep the Service secure.</li>
          <li>
            Send service-related communications, such as email verification and password resets.
          </li>
          <li>Analyze usage to improve product quality and troubleshooting.</li>
          <li>Comply with legal obligations and enforce our Terms of Service.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="4. Sharing Your Information">
        <p>
          We do not sell your personal information. We share information only with service providers
          who help us operate the Service, including:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Cloud infrastructure and database providers that host the Service.</li>
          <li>
            Speech-to-text and AI model providers that process interview audio and generate
            evaluations.
          </li>
          <li>Payment processors when you purchase a subscription.</li>
          <li>Error monitoring and analytics providers that help us maintain reliability.</li>
        </ul>
        <p>
          These providers access personal information only to perform work on our behalf and are
          bound by confidentiality obligations. We may also disclose information when required by
          law or in connection with a merger, acquisition, or sale of assets.
        </p>
      </LegalSection>

      <LegalSection heading="5. Data Retention">
        <p>
          We retain your account information for as long as your account is active. Interview
          recordings and evaluations are retained to power your progress history and are deleted
          when you request deletion of your account. Logs and analytics data may be retained for
          shorter periods as needed for security and troubleshooting.
        </p>
      </LegalSection>

      <LegalSection heading="6. Your Rights">
        <p>
          Depending on your jurisdiction, you may have the right to access, correct, export,
          restrict, or delete the personal information we hold about you. You can exercise most of
          these rights by contacting us at{" "}
          <span className="text-foreground">support@tayari.ai</span>. We will respond to verified
          requests within the timeframe required by applicable law.
        </p>
      </LegalSection>

      <LegalSection heading="7. Security">
        <p>
          We use industry-standard technical and organizational measures to protect your
          information, including encryption in transit, secure password hashing, and access
          controls. No method of transmission or storage is completely secure, and we cannot
          guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection heading="8. Children's Privacy">
        <p>
          The Service is not directed to individuals under the age of 13, and we do not knowingly
          collect personal information from children. If you believe a child has provided us
          personal information, please contact us so we can delete it.
        </p>
      </LegalSection>

      <LegalSection heading="9. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. When we do, we will revise the "Last
          updated" date at the top of this page and, where required by law, notify you by email or
          an in-product notice.
        </p>
      </LegalSection>

      <LegalSection heading="10. Contact Us">
        <p>
          If you have questions about this Privacy Policy or your data, contact us at{" "}
          <span className="text-foreground">support@tayari.ai</span>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
