import type { Metadata } from "next";

import { LegalLayout, LegalSection } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — Tayari AI",
  description: "The terms and conditions that govern your use of the Tayari AI service.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="August 14, 2026">
      <LegalSection heading="1. Acceptance of Terms">
        <p>
          By accessing or using Tayari AI (the "Service"), you agree to be bound by these Terms of
          Service (the "Terms"). If you do not agree to these Terms, do not use the Service.
        </p>
      </LegalSection>

      <LegalSection heading="2. Eligibility">
        <p>
          You must be at least 13 years old to use the Service. By using the Service, you represent
          that you meet this requirement and that you have the authority to accept these Terms.
        </p>
      </LegalSection>

      <LegalSection heading="3. Your Account">
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and
          for all activity that occurs under your account. You agree to notify us promptly of any
          unauthorized use. We may suspend or terminate accounts that violate these Terms.
        </p>
      </LegalSection>

      <LegalSection heading="4. Use of the Service">
        <p>
          The Service provides AI-powered interview practice, including simulated interviews, voice
          interaction, and automated evaluations. You agree to use the Service only for lawful
          purposes and not to:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Attempt to disrupt, reverse engineer, or gain unauthorized access to the Service.</li>
          <li>Abuse, harass, or defraud other users.</li>
          <li>Upload or transmit malicious code or content.</li>
          <li>Use the Service to infringe the intellectual property rights of others.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="5. Subscriptions and Payments">
        <p>
          Certain features may require a paid subscription. Subscription fees, billing cycles, and
          renewals are described at the point of purchase. You authorize us (or our payment
          processor) to charge the payment method you provide. Unless required otherwise by law,
          subscription fees are non-refundable except as required by applicable consumer laws.
        </p>
        <p>
          You may cancel your subscription at any time; access will continue until the end of the
          current billing period. We may change pricing with advance notice.
        </p>
      </LegalSection>

      <LegalSection heading="6. Intellectual Property">
        <p>
          The Service, including its design, text, graphics, software, and AI systems, is owned by
          Tayari AI or its licensors and is protected by intellectual property laws. You retain
          ownership of the content you provide, and you grant us a limited license to store and
          process that content solely to provide the Service to you.
        </p>
      </LegalSection>

      <LegalSection heading="7. AI-Generated Content">
        <p>
          Evaluations, feedback, and interview questions are generated by automated systems and may
          not always be accurate or complete. The Service is provided for practice and educational
          purposes and does not constitute professional career advice. You are responsible for how
          you use AI-generated content.
        </p>
      </LegalSection>

      <LegalSection heading="8. Disclaimer of Warranties">
        <p>
          The Service is provided "as is" and "as available" without warranties of any kind, whether
          express or implied, including implied warranties of merchantability, fitness for a
          particular purpose, and non-infringement. We do not warrant that the Service will be
          uninterrupted, error-free, or secure.
        </p>
      </LegalSection>

      <LegalSection heading="9. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, Tayari AI shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or any loss of profits, data, or
          goodwill, arising out of or related to your use of the Service.
        </p>
      </LegalSection>

      <LegalSection heading="10. Termination">
        <p>
          We may suspend or terminate your access to the Service, in whole or in part, at our
          discretion and with or without notice, for any violation of these Terms or for security
          reasons. You may stop using the Service and delete your account at any time.
        </p>
      </LegalSection>

      <LegalSection heading="11. Changes to These Terms">
        <p>
          We may update these Terms from time to time. We will post the revised Terms on this page
          and update the "Last updated" date. Continued use of the Service after changes take effect
          constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection heading="12. Contact Us">
        <p>
          Questions about these Terms? Contact us at{" "}
          <span className="text-foreground">support@tayari.ai</span>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
